"""add column user.is_admin

Revision ID: ac246dea74cd
Revises: 69e834c3bb7f
Create Date: 2022-05-15 12:03:14.287501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac246dea74cd'
down_revision = '69e834c3bb7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.String(length=150), nullable=True))
    op.add_column('User', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('User', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('User', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('User', 'phone_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_unique_constraint(None, 'User', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.alter_column('User', 'phone_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('User', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('User', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('User', 'is_admin')
    op.drop_column('User', 'password')
    # ### end Alembic commands ###
