"""empty message

Revision ID: 22c2fce5f66d
Revises: ac246dea74cd
Create Date: 2022-05-18 18:10:02.388410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c2fce5f66d'
down_revision = 'ac246dea74cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dl', sa.String(length=20), nullable=True),
    sa.Column('national_id', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dl'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('Wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('balance', sa.Float(precision=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('Vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=1), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['Driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vehicle')
    op.drop_table('Wallet')
    op.drop_table('Driver')
    # ### end Alembic commands ###
